name: Bourse
run-name: Deploy
on:
  push:
    branches:
      - main
      
jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror to server
    steps:
      - name: Git pull on VPS
        uses: easingthemes/ssh-run@v0.4.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/bourse-forex
            git pull
    
  deploy:
    runs-on: ubuntu-latest
    needs: mirror
    name: deploy on vps
    steps:
      - name: Push on remote repo
        uses: easingthemes/ssh-run@v0.4.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo systemctl stop bourse
            sudo systemctl start bourse
