name: Bourse
run-name: Deploy
on:
  push:
    branches:
      - main
      
jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror to server
    steps:
      - name: Git pull on VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          ssh_host: ${{ secrets.HOST }}
          ssh_user: ${{ secrets.USER }}
          ssh_port: ${{ secrets.PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo apt-get update && sudo apt-get upgrade -y
            sudo systemctl stop bourse
            cd /home/ubuntu/bourse
            git pull
    
  deploy:
    runs-on: ubuntu-latest
    needs: mirror
    name: deploy on vps
    steps:
      - name: Push on remote repo
        uses: appleboy/ssh-action@v0.1.6
        with:
          ssh_host: ${{ secrets.HOST }}
          ssh_user: ${{ secrets.USER }}
          ssh_port: ${{ secrets.PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo systemctl start bourse
