name: SSH connection

on:
  push:
    branches:
      - main

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH
      run: apt-get update && apt-get install -y openssh-client

    - name: SSH connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        ssh_host: 51.254.112.184
        ssh_user: ubuntu
        ssh_port: 22
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo "Connected via SSH"